services:
  redis:
    image: redis:7.4
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  outline:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - outline_data:/var/lib/outline/data
volumes:
  postgres_data:
  redis_data:
  outline_data:
